"""Render editable, sourced narration scripts to local MP3s using macOS speech.
Requires the Vietnamese Linh voice, say, ffmpeg and ffprobe. No API key needed.
"""
import argparse
import concurrent.futures
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(job):
    region, chapter, voice, rate = job
    target = ROOT/'dist/assets/audio/narration'/region/f'{chapter["id"]}.mp3'
    fingerprint = hashlib.sha256(json.dumps([chapter['text'], voice, rate, 'mp3-96k-loudnorm-v1'], ensure_ascii=False).encode()).hexdigest()
    cache = ROOT/'data/narration'/region/f'{chapter["id"]}.sha256'
    if not target.is_file() or not cache.is_file() or cache.read_text() != fingerprint:
        target.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix='atlas-narration-') as directory:
            directory = Path(directory)
            text = directory/'script.txt'
            text.write_text(chapter['text'], encoding='utf-8')
            speech = directory/'speech.aiff'
            output = directory/'speech.mp3'
            subprocess.run(['say', '-v', voice, '-r', str(rate), '-f', str(text), '-o', str(speech)], check=True)
            subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-i', str(speech),
                '-af', 'loudnorm=I=-18:TP=-2:LRA=7', '-ar', '44100', '-ac', '1', '-b:a', '96k', str(output)], check=True)
            shutil.copy2(output, target)
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(fingerprint)
    duration = float(subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries',
        'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', str(target)], text=True))
    if duration < 10:
        raise ValueError('Narration is unexpectedly short')
    print(f'Ready: {region}/{chapter["id"]} ({duration:.0f}s)', flush=True)
    return {**chapter, 'src':str(target.relative_to(ROOT/'dist')), 'duration':round(duration, 2), 'script_sha256':fingerprint}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--voice', help='Installed Vietnamese macOS voice; default from script')
    parser.add_argument('--rate', type=int, help='Words per minute; default from script')
    args = parser.parse_args()
    for program in ['say', 'ffmpeg', 'ffprobe']:
        if not shutil.which(program):
            raise SystemExit(f'Missing {program}; preserve the scripts and install a speech renderer first.')
    regions = [json.loads(path.read_text()) for path in sorted((ROOT/'narration').glob('*.json'))]
    catalog = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:
        for region in regions:
            voice, rate = args.voice or region['voice'], args.rate or region['rate']
            chapters = list(pool.map(render, [(region['region_id'], c, voice, rate) for c in region['chapters']]))
            catalog[region['region_id']] = {'name':region['region_name'], 'voice':voice, 'chapters':chapters}
    (ROOT/'dist/narration-catalog.js').write_text('// Generated by scripts/generate_narration.py; edit narration/*.json.\nexport const narrations = '+json.dumps(catalog, ensure_ascii=False, separators=(',', ':'))+';\n')
    print('Published 16 narration tracks and text/source catalog.')


if __name__ == '__main__':
    main()
