import {FOODS,LEVELS,COOK_SECONDS,HANDWASH_SECONDS,MAX_EXPOSURE,createItem,isRawMeat,touchFood,prepareItem,cookItem,foodRisk,starsFor,seededRandom} from './rules.js';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');

// Raster assets keep all gameplay state, coordinates and collisions code-native.
const art={};
if(typeof Image!=='undefined'){
 const names=['characters','chicken','veg','fruit','sink','rawboard','cleanboard','stove','serve','trash','power','water','plant','food-chicken-raw','food-chicken','food-salad-raw','food-salad','food-fruit-raw','food-fruit'];
 for(const name of names){const img=new Image();img.onload=()=>{art[name]=img;};img.onerror=()=>console.warn('Asset unavailable, using fallback:',name);img.src=`assets/sprites/${name}.png`;}
}
function sprite(name,x,y,width,height=width){const img=art[name];if(!img)return false;ctx.drawImage(img,x-width/2,y-height/2,width,height);return true;}
function foodMarkup(kind,raw=false){return `<img class="food-sprite" src="assets/sprites/food-${kind}${raw?'-raw':''}.png" alt="">`;}
function drawCharacterSprite(x,y,dir,moving,helper){
 const img=art.characters;if(!img)return false;
 const col={down:0,left:1,right:2,up:3}[dir]??0;
 const walk=moving&&Math.sin(g.elapsed*12)>0;
 const row=(helper?2:0)+(walk?1:0);
 const bob=moving?Math.abs(Math.sin(g.elapsed*12))*1.4:Math.sin(g.elapsed*2)*.4;
 ellipse(x,y+20,21,7,'#28483625');
 ctx.save();ctx.translate(x,y+20);if(!helper&&g.busy)ctx.rotate(Math.sin(g.elapsed*9)*.025);ctx.drawImage(img,col*96,row*112,96,112,-38,-88-bob,76,89);ctx.restore();
 if(!helper&&g.busy){const washing=g.busy.label.includes('Rửa');for(let i=0;i<5;i++){const phase=(g.elapsed*1.2+i*.2)%1;const px=x+(i-2)*8,py=y-16-phase*22;if(washing){ellipse(px,py,2+phase*2,3+phase*2,`rgba(129,194,211,${.8*(1-phase)})`);}else if(i<3){text('✦',px,py,9,'#dfb15e');}}}
 return true;
}
function drawStationSprite(s){
 if(!art[s.id])return false;
 const locked=(s.id==='veg'&&g.index<1)||(s.id==='fruit'&&g.index<2),active=nearest()?.id===s.id;
 const base=s.y+s.h/2;
 if(active){rect(s.x-s.w/2-9,s.y-s.h/2-7,s.w+18,s.h+14,'#edbf684a',16);ctx.strokeStyle='#d49b43';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(s.x-s.w/2-9,s.y-s.h/2-7,s.w+18,s.h+14,16);ctx.stroke();}
 ellipse(s.x,base-5,s.w*.47,13,'#304d3420');
 const box=s.id==='serve'?184:s.id==='chicken'?140:s.id==='power'?76:s.id==='trash'?96:s.id==='water'?120:s.w+20;
 ctx.save();if(locked)ctx.globalAlpha=.4;sprite(s.id,s.x,base-box/2,box);ctx.restore();
 if(s.id==='chicken'){rect(s.x+27,base-30,44,20,g.fridgeOff?'#b66341':'#245a4d',5);text(g.fridgeOff?'⚡':'4°C',s.x+49,base-15,12,'#fff7de');}
 if(s.dirty){rect(s.x-48,base-15,96,18,'#fff0d6',6);text('CẦN VỆ SINH',s.x,base-2,10,'#925b35');}
 if(s.type==='sink'&&g.waterOff){rect(s.x-29,base-36,58,24,'#fff0d6',6);text('HẾT NƯỚC',s.x,base-20,9,'#985e3a');}
 if(s.type==='stove'&&s.item){foodIcon('chicken',s.x+26,base-box*.65,32,s.item.stage!=='cooked');rect(s.x-54,base-9,108,6,'#426454',3);rect(s.x-54,base-9,108*Math.min(1,s.cook/COOK_SECONDS),6,'#f2bb6a',3);for(let i=0;i<3;i++){const phase=(g.elapsed*.65+i*.3)%1;ellipse(s.x+24+(i-1)*9,base-box*.65-14-phase*25,3+phase*3,6+phase*3,`rgba(255,255,246,${.6*(1-phase)})`);}if(s.cook>=COOK_SECONDS){rect(s.x-47,base-box+8,94,22,'#fff8df',7);text(s.item.verified?'✓ 74°C':'ĐO NHIỆT',s.x,base-box+24,11,'#456b50');}}
 const label=locked?'CHƯƠNG '+(s.kind==='salad'?'02':'03'):s.name;
 const lw=Math.max(76,label.length*6+14);rect(s.x-lw/2,base+7,lw,23,active?'#174f45':'#fff9ebed',7);text(label,s.x,base+23,11,active?'#fff9e7':'#496950');
 return true;
}

const colors={green:'#174f45',mint:'#a8c9b0',floor:'#e9e6d6',ink:'#244c40',orange:'#f1ad68'};
let saved;try{saved=JSON.parse(localStorage.getItem('bep-safe-v1'))||{};}catch{saved={};}if(!Array.isArray(saved.stars))saved.stars=[0,0,0];if(!Number.isFinite(saved.unlocked))saved.unlocked=0;saved.unlocked=Math.max(0,Math.min(2,saved.unlocked));
let g=null,keys={},last=0,toastTimer,audio=null,sound=false,touch={x:0,y:0},walkTarget=null,walkPath=[],modalResume=false;
const stationsBase=[
{id:'chicken',name:'TỦ GÀ SỐNG',x:92,y:157,w:126,h:78,type:'stock',kind:'chicken'},
{id:'veg',name:'KHO RAU',x:92,y:310,w:126,h:76,type:'stock',kind:'salad'},
{id:'fruit',name:'KHO TRÁI CÂY',x:92,y:458,w:126,h:76,type:'stock',kind:'fruit'},
{id:'sink',name:'BỒN RỬA',x:288,y:130,w:134,h:72,type:'sink'},
{id:'rawboard',name:'BÀN SỐNG',x:470,y:256,w:118,h:74,type:'board'},
{id:'cleanboard',name:'BÀN RAU',x:470,y:422,w:118,h:74,type:'board'},
{id:'stove',name:'BẾP NƯỚNG',x:645,y:130,w:140,h:72,type:'stove'},
{id:'serve',name:'QUẦY PHỤC VỤ',x:850,y:310,w:120,h:130,type:'serve'},
{id:'trash',name:'THÙNG BỎ',x:670,y:516,w:80,h:70,type:'trash'},
{id:'power',name:'CẦU DAO',x:89,y:570,w:84,h:44,type:'power'},
{id:'water',name:'NƯỚC DỰ PHÒNG',x:305,y:540,w:120,h:64,type:'water'}];
function persist(){try{localStorage.setItem('bep-safe-v1',JSON.stringify(saved));}catch{toast('Trình duyệt không cho lưu tiến độ. Bạn vẫn có thể chơi bình thường.');}}
function beep(freq=500,duration=.08){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(.045,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3800);}
function openModal(html,resume=false){if(g?.running)g.paused=true;keys={};touch={x:0,y:0};walkTarget=null;modalResume=resume;$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function closeModal(){ $('modal').close();if(g?.running)g.paused=false;modalResume=false;canvas.focus({preventScroll:true});}
function heading(title){return `<div class="modal-top"><h2>${title}</h2><button class="modal-close" data-close aria-label="Đóng">×</button></div>`;}
function renderHome(){ $('home').classList.remove('hidden');$('play').classList.add('hidden');$('levels').innerHTML=LEVELS.map((l,i)=>`<button class="level-card" data-level="${i}" ><span class="number">CHƯƠNG 0${i+1}</span><span class="stars">${'★'.repeat(saved.stars[i])+'☆'.repeat(3-saved.stars[i])}</span><span class="level-symbol">${l.icon}</span><h3>${l.name}</h3><p>${l.subtitle}</p><div class="card-bottom"><span>${l.target} món an toàn · ${Math.floor(l.duration/60)}:${String(l.duration%60).padStart(2,'0')}</span><span>Vào bếp →</span></div></button>`).join('');}
function guide(){openModal(heading('Bí kíp của biệt đội')+`<p class="modal-copy">Di chuyển bằng <b>WASD / phím mũi tên</b>. Đến gần trạm và nhấn <b>E</b>. Bạn cũng có thể bấm vào trạm để đi đến đó, rồi bấm Thao tác. Trên điện thoại dùng các nút hướng.</p><div class="recipes"><div class="recipe"><b>🍗 Gà nướng</b>Tủ gà → bàn sống → bếp (đặt gà xuống) → rửa tay → trở lại bếp đo nhiệt độ → lấy gà khi đạt 74°C → quầy.</div><div class="recipe"><b>🥗 Salad / 🍉 Trái cây</b>Kho → bồn rửa (nước an toàn) → bàn rau sạch → quầy. Rửa tay trước khi cầm đồ ăn sẵn!</div><div class="recipe"><b>🧼 Vệ sinh & đồng đội</b>Tay trống tại bồn rửa: rửa tay. Tay trống tại bàn: rửa dụng cụ. Nhấn <b>H</b> để Nam vệ sinh cả hai bàn (có hồi chiêu). Nam không rửa tay thay bạn.</div><div class="recipe"><b>⚡ Sự cố & món để lâu</b>Cúp điện: đến cầu dao khôi phục tủ lạnh. Thiếu nước: kích hoạt nước dự phòng rồi vệ sinh tay. Thanh đồng hồ trên món là thời gian mô phỏng; món quá hạn phải bỏ. Thùng bỏ nhận mọi món.</div></div><p class="modal-copy">Món không an toàn bị giữ lại ở quầy, bạn mất uy tín và cần khắc phục. Phục vụ đủ mục tiêu để mở chương tiếp theo. ⭐⭐: đạt mục tiêu, tối đa 1 lỗi. ⭐⭐⭐: vượt mục tiêu 2 món và không có lỗi.</p><div class="modal-buttons"><button class="primary" data-close>Đã hiểu!</button></div>`,!!g?.running);}
function book(){openModal(heading('Sổ tay bếp an toàn')+`<div class="recipes"><div class="recipe"><b>01 · Giữ sạch</b>Rửa tay bằng xà phòng ít nhất 20 giây ngoài đời; rửa dụng cụ sau khi xử lý thực phẩm sống.</div><div class="recipe"><b>02 · Tách sống và chín</b>Dùng thớt riêng cho thịt sống và thực phẩm ăn ngay. Không thể nhìn bằng mắt để biết món có nhiễm vi sinh vật hay không.</div><div class="recipe"><b>03 · Nấu kỹ</b>Dùng nhiệt kế thực phẩm. Trong game, món gà cần đạt nhiệt độ bên trong ít nhất 74°C. Không dựa vào màu món ăn. Không rửa gà sống vì nước bắn có thể làm lan nhiễm.</div><div class="recipe"><b>04 · Bảo quản an toàn</b>Giữ tủ lạnh khoảng 4°C hoặc thấp hơn. Theo CDC, thực phẩm dễ hỏng không để ngoài quá 2 giờ, hoặc 1 giờ khi môi trường trên khoảng 32°C. Mất điện cần kiểm tra thời gian và nhiệt độ bảo quản.</div><div class="recipe"><b>05 · Nước và nguyên liệu an toàn</b>Dùng nước an toàn, rửa rau quả dưới vòi nước; kiểm tra nguồn gốc, nhãn và hướng dẫn bảo quản.</div></div><p class="sources">Game đơn giản hóa bếp và tăng tốc thời gian. 2 giây rửa tay, 10 giây nấu, đồng hồ 50 giây trên món là cơ chế chơi; không phải thời gian thực tế. “Bỏ món” là xử lý một rủi ro đã xác định trong mô phỏng, không suy đoán chỉ từ vẻ ngoài.</p><p class="sources">Nguồn: <a href="https://www.who.int/publications/i/item/9789241594639" target="_blank" rel="noopener">WHO · Five keys to safer food</a> · <a href="https://www.cdc.gov/food-safety/prevention/index.html" target="_blank" rel="noopener">CDC · Preventing Food Poisoning</a></p>`,!!g?.running);}
function startLevel(index,seed=Date.now()>>>0){if(!Number.isInteger(index)||index<0||index>=LEVELS.length)return;const level=LEVELS[index];const rng=seededRandom(seed);g={index,level,seed,rng,time:level.duration,elapsed:0,score:0,reputation:100,served:0,missed:0,mistakes:0,waste:0,orders:[],nextOrder:5,nextId:1,player:{x:370,y:350,dir:'down',moving:false},held:null,dirtyHands:false,stations:stationsBase.map(s=>({...s,dirty:false,item:null,cook:0})),busy:null,helper:0,helperCooldown:0,eventDone:false,eventAt:45+rng()*20,fridgeOff:false,waterOff:false,fridgeTime:0,stockUnsafe:false,logs:[],running:true,paused:true,relaxed:$('relaxed').checked,uiClock:0};if(index===1){g.stations.find(s=>s.id==='rawboard').y=295;g.stations.find(s=>s.id==='cleanboard').y=457;}if(index===2&&rng()>.5){g.stations.find(s=>s.id==='sink').x=450;g.stations.find(s=>s.id==='stove').x=275;}keys={};walkTarget=null;touch={x:0,y:0};$('home').classList.add('hidden');$('play').classList.remove('hidden');$('level-label').textContent=`CHƯƠNG 0${index+1} · HỘI CHỢ TRƯỜNG`;$('level-title').textContent=level.name;$('goal').textContent=`Mục tiêu: ${level.target} món an toàn`;$('tip').textContent=index===0?'Mẹo: đặt gà lên bếp rồi rửa tay trong lúc chờ nấu.':index===1?'Rửa tay sau khi chạm gà sống. Dùng bàn rau riêng cho món ăn ngay.':'Thấy tủ lạnh mất điện? Ưu tiên khôi phục cầu dao!';addOrder(level.menu[0]);updateUI();draw();openModal(heading(level.name)+`<p class="modal-copy">${['Linh: “Gian hàng đã sẵn sàng! Cậu lo bếp, Nam sẽ giúp vệ sinh dụng cụ. Hãy phục vụ những phần gà thật an toàn nhé.”','Nam: “Khách muốn thêm salad. Đừng để gà sống và rau ăn ngay dùng chung dụng cụ. Tớ luôn sẵn sàng giúp!”','Linh: “Hội chợ đông nhất hôm nay! Có cả trái cây và thiết bị có thể trục trặc. Cả đội trông cậy vào cậu.”'][index]}</p><div class="tutorial-step"><b>Phục vụ ${level.target} món trong ${Math.floor(level.duration/60)} phút ${level.duration%60?level.duration%60+' giây':''}.</b><br>${index===0?'Gà → bàn sống → bếp → rửa tay → đo nhiệt độ → lấy món → quầy.':'Lấy nguyên liệu theo đơn hàng. Kiểm tra công thức khi cần.'}</div><p class="sources">Mã lượt chơi: ${seed} · ${g.relaxed?'Thư giãn: thời gian chờ của khách dài hơn.':'Thử thách: theo dõi hàng chờ và ưu tiên công việc.'}</p><div class="modal-buttons"><button class="primary" id="begin">Bắt đầu ca bếp →</button><button class="quiet" id="intro-guide">Xem cách chơi</button></div>`);}
function addOrder(kind){if(g.orders.length>=4)return;const patience=g.level.patience*(g.relaxed?1.65:1);g.orders.push({id:g.nextId++,kind:kind||g.level.menu[Math.floor(g.rng()*g.level.menu.length)],time:patience,max:patience});}
function nearest(){let best=null,dist=Infinity;for(const s of g.stations){if((s.id==='veg'&&g.index<1)||(s.id==='fruit'&&g.index<2))continue;const d=Math.hypot(g.player.x-s.x,g.player.y-s.y);if(d<dist){dist=d;best=s;}}return dist<Math.max(best?.w||0,best?.h||0)/2+65?best:null;}
function busy(seconds,label,done){g.busy={seconds,total:seconds,label,done};beep(430);}
function riskLog(reason){const texts={cross:'Nhiễm chéo: tay hoặc dụng cụ sau khi chạm gà sống đã tiếp xúc món ăn sẵn. Rửa tay và dùng bàn riêng.',cook:'Gà chưa được nấu và kiểm tra đủ: dùng nhiệt kế, đạt 74°C trước khi lấy món.',storage:'Món hoặc nguyên liệu đã vượt giới hạn bảo quản mô phỏng. Bỏ món và khôi phục tủ lạnh.',prepare:'Món chưa hoàn thành sơ chế: rau/quả cần rửa bằng nước an toàn và chuẩn bị trên bàn sạch.'};g.logs.push(texts[reason]);g.mistakes++;g.reputation=Math.max(0,g.reputation-15);toast('⛔ '+texts[reason]);beep(150,.25);}
function interact(){if(!g?.running||g.paused||g.busy)return;const s=nearest();if(!s){toast('Đến gần một trạm hoặc bấm vào trạm để di chuyển.');return;}walkTarget=null;const item=g.held;
if(s.type==='stock'){if(item){toast('Bạn đang cầm đồ. Hoàn thành món hoặc bỏ tại thùng trước.');return;}if(s.kind==='chicken'&&g.stockUnsafe){toast('Lô gà đã mất điều kiện bảo quản. Khôi phục cầu dao để nhận lô mới.');return;}g.held=createItem(s.kind);g.dirtyHands=touchFood(g.held,g.dirtyHands);beep(600);}
else if(s.type==='sink'){if(g.waterOff){toast('Nước chính đang thiếu. Đến trạm nước dự phòng.');return;}if(!item){busy(HANDWASH_SECONDS,'Rửa tay với xà phòng',()=>{g.dirtyHands=false;toast('Tay sạch! Ngoài đời: rửa ít nhất 20 giây.');});}else if(item.kind==='chicken'){toast('Không rửa gà sống: nước bắn có thể làm lan nhiễm. Đến bàn sống.');}else if(item.stage==='raw'){busy(2,'Rửa rau/quả bằng nước an toàn',()=>{item.stage='washed';toast('Đã rửa. Đưa đến bàn rau sạch để chuẩn bị.');});}else{toast('Bồn rửa dùng cho tay trống hoặc rau/quả chưa rửa.');}}
else if(s.type==='board'){if(!item){if(!s.dirty){toast('Dụng cụ đã sạch.');return;}if(g.waterOff){toast('Cần nước an toàn để rửa. Kích hoạt nước dự phòng.');return;}busy(2.5,'Rửa thớt và dụng cụ',()=>{s.dirty=false;toast('Dụng cụ đã sạch.');});}else{if(!['raw','washed'].includes(item.stage)){toast('Món đã sơ chế. Đưa đến bếp hoặc quầy.');return;}if(item.kind!=='chicken'&&item.stage!=='washed'){toast('Rửa rau/quả ở bồn trước khi sơ chế.');return;}busy(2.2,'Sơ chế '+FOODS[item.kind].name,()=>{g.dirtyHands=touchFood(item,g.dirtyHands);const result=prepareItem(item,s.dirty);s.dirty=result.boardDirty;if(item.kind==='chicken'&&s.id==='cleanboard')toast('Bạn vừa dùng bàn rau cho gà sống. Cần vệ sinh trước khi dùng cho rau!');else toast(item.kind==='chicken'?'Đã sơ chế gà. Đặt lên bếp nướng.':'Đã chuẩn bị món. Mang đến quầy!');});}}
else if(s.type==='stove'){if(s.item){if(item){toast('Tay cần trống để đo hoặc lấy món trên bếp.');return;}if(!s.item.verified){busy(1,'Đo nhiệt độ bên trong',()=>{const temp=Math.floor(20+54*Math.min(1,s.cook/COOK_SECONDS));if(temp>=74){s.item.verified=true;toast('🌡 74°C — gà đạt nhiệt độ an toàn. Nhấn E để lấy món.');}else toast(`🌡 ${temp}°C — chưa đủ. Tiếp tục nấu rồi đo lại.`);});}else{g.held=s.item;s.item=null;s.cook=0;g.dirtyHands=touchFood(g.held,g.dirtyHands);beep(740);}}else if(item?.kind==='chicken'&&item.stage==='cut'){s.item=item;s.cook=0;g.held=null;toast('Đang nấu! Tranh thủ rửa tay ở bồn trước khi lấy gà chín.');}else toast('Bếp nhận gà đã sơ chế tại bàn sống.');}
else if(s.type==='serve'){if(!item){toast('Mang một món hoàn thành đến quầy.');return;}const risk=foodRisk(item);if(risk){riskLog(risk);return;}const order=g.orders.find(o=>o.kind===item.kind);if(!order){toast('Chưa có khách đặt món này. Giữ món hoặc đợi đơn phù hợp.');return;}g.orders=g.orders.filter(o=>o.id!==order.id);g.served++;g.score+=100+Math.round(50*order.time/order.max);g.held=null;g.reputation=Math.min(100,g.reputation+3);toast('✦ Phục vụ an toàn! '+FOODS[item.kind].name);beep(880,.14);}
else if(s.type==='trash'){if(!item){toast('Không có món cần bỏ.');return;}g.held=null;g.waste++;toast('Đã bỏ món. Rửa tay nếu bạn vừa xử lý gà sống.');}
else if(s.type==='power'){if(!g.fridgeOff){toast('Tủ lạnh đang hoạt động ở 4°C.');return;}busy(3,'Khôi phục điện và kiểm tra tủ lạnh',()=>{g.fridgeOff=false;g.stockUnsafe=false;g.fridgeTime=0;toast('⚡ Tủ lạnh hoạt động. Đã kiểm tra và thay lô nguyên liệu bị ảnh hưởng.');});}
else if(s.type==='water'){if(!g.waterOff){toast('Nước chính đang an toàn, dự phòng chưa cần dùng.');return;}busy(2,'Mở nguồn nước an toàn dự phòng',()=>{g.waterOff=false;toast('💧 Có nước an toàn. Rửa tay và dụng cụ trước khi tiếp tục.');});}updateUI();}
function askHelper(){if(!g?.running||g.paused)return;if(g.waterOff){toast('Nam cần nước an toàn. Kích hoạt nước dự phòng trước.');return;}if(g.helper>0||g.helperCooldown>0){toast('Nam đang bận hoặc cần nghỉ một chút.');return;}g.helper=5;g.helperCooldown=25;toast('Nam: “Để tớ rửa dụng cụ! Cậu tập trung vào đơn hàng nhé.”');beep(680);}
function context(){const s=nearest();if(g.busy)return g.busy.label+'…';if(!s)return 'Đến gần trạm hoặc bấm vào trạm để đi đến đó.';if(s.type==='stock')return `${s.name} · E lấy ${FOODS[s.kind].raw.toLowerCase()}`;if(s.type==='sink')return g.held?'E rửa rau / quả':'E rửa tay với xà phòng';if(s.type==='board')return g.held?`E sơ chế tại ${s.id==='rawboard'?'bàn sống':'bàn rau'}`:'E vệ sinh dụng cụ';if(s.type==='stove')return s.item?(!s.item.verified?'E đo nhiệt độ bên trong':'E lấy món gà chín'):'E đặt gà đã sơ chế lên bếp';if(s.type==='serve')return 'E phục vụ món cho khách';if(s.type==='trash')return 'E bỏ món đang cầm';if(s.type==='power')return 'E khôi phục điện / kiểm tra tủ lạnh';return 'E kích hoạt nước dự phòng';}
function updateUI(){if(!g)return;const sec=Math.ceil(g.time);$('timer').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;$('score').textContent=g.score;$('reputation').textContent=g.reputation;$('served').textContent=`${g.served}/${g.level.target} món`;$('orders').innerHTML=g.orders.length?g.orders.map(o=>`<div class="order"><span class="food-emoji">${foodMarkup(o.kind)}</span><div class="order-details"><b>${FOODS[o.kind].name}</b><div class="patience"><i style="width:${o.time/o.max*100}%;background:${o.time/o.max<.3?'#db875e':'#77aa85'}"></i></div><small>Khách #${o.id} · ${Math.ceil(o.time)}s</small></div></div>`).join(''):'<p class="sources">Đang chờ khách mới…</p>';const stages={raw:'Chưa sơ chế',washed:'Đã rửa',cut:'Đã sơ chế',ready:'Sẵn sàng',cooked:g.held?.verified?'Đã đo 74°C':'Cần đo nhiệt độ'};$('held').innerHTML=g.held?`${foodMarkup(g.held.kind,['raw','washed','cut'].includes(g.held.stage))}<span>${FOODS[g.held.kind].name}<small>${stages[g.held.stage]}</small></span>`:'✋ Tay trống';$('hands').textContent=g.dirtyHands?'🧼 Cần rửa tay sau khi tiếp xúc gà sống':'✓ Tay sạch';$('hands').style.color=g.dirtyHands?'#a15c35':'#55705b';$('helper-status').textContent=g.helper>0?'Đang vệ sinh dụng cụ…':g.helperCooldown>0?`Nghỉ ${Math.ceil(g.helperCooldown)} giây`:'Sẵn sàng phụ bếp!';$('help').disabled=g.helper>0||g.helperCooldown>0;$('context').textContent=context();const events=[];if(g.waterOff)events.push('💧 Thiếu nước! Đến trạm NƯỚC DỰ PHÒNG.');if(g.fridgeOff)events.push(`⚡ Tủ lạnh mất điện! Đến CẦU DAO. ${g.stockUnsafe?'Lô gà đã bị giữ lại.':'Ưu tiên xử lý ngay.'}`);$('event-banner').classList.toggle('hidden',!events.length);$('event-banner').textContent=events.join(' ');}
function canMove(x,y){if(x<42||x>948||y<90||y>605)return false;return !g.stations.some(s=>x>s.x-s.w/2-15&&x<s.x+s.w/2+15&&y>s.y-s.h/2-15&&y<s.y+s.h/2+15);}
function setWalkPath(target){
walkPath=[];walkTarget=null;if(!target)return;
const step=20,cols=51,rows=33;
const cell=p=>({x:Math.round(p.x/step),y:Math.round(p.y/step)});
const start=cell(g.player),end=cell(target),id=p=>p.y*cols+p.x;
const queue=[start],prev=new Map([[id(start),null]]);let found=null;
for(let at=0;at<queue.length;at++){const p=queue[at];if(p.x===end.x&&p.y===end.y){found=p;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy};if(n.x<0||n.x>=cols||n.y<0||n.y>=rows||prev.has(id(n))||!canMove(n.x*step,n.y*step))continue;prev.set(id(n),p);queue.push(n);}}
if(!found){toast('Đường đi bị chắn. Dùng phím hoặc nút hướng để đi vòng.');return;}
let p=found;const path=[];while(p){path.unshift({x:p.x*step,y:p.y*step});p=prev.get(id(p));}path.push(target);walkPath=path;walkTarget=walkPath.shift();
}
function update(dt){if(!g||g.paused||!g.running)return;g.time=Math.max(0,g.time-dt);g.elapsed+=dt;if(g.busy){g.busy.seconds-=dt;if(g.busy.seconds<=0){const done=g.busy.done;g.busy=null;done();}}else{let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+touch.x,dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+touch.y;if(walkTarget&&!dx&&!dy){dx=walkTarget.x-g.player.x;dy=walkTarget.y-g.player.y;if(Math.hypot(dx,dy)<8){walkTarget=walkPath.shift()||null;dx=dy=0;}}else if(dx||dy){walkTarget=null;walkPath=[];}const len=Math.hypot(dx,dy);g.player.moving=len>0;if(len){dx/=len;dy/=len;const speed=205;let nx=g.player.x+dx*speed*dt,ny=g.player.y+dy*speed*dt;let moved=false;if(canMove(nx,g.player.y)){g.player.x=nx;moved=true;}if(canMove(g.player.x,ny)){g.player.y=ny;moved=true;}if(!moved)walkTarget=null;g.player.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');}}
const stove=g.stations.find(s=>s.id==='stove');if(stove.item){stove.cook+=dt;if(stove.cook>=COOK_SECONDS&&stove.item.stage!=='cooked')cookItem(stove.item);if(stove.item.stage==='cooked')stove.item.exposure+=dt;}if(g.held)g.held.exposure+=dt;
for(const o of g.orders)o.time-=dt;const expired=g.orders.filter(o=>o.time<=0);if(expired.length){g.missed+=expired.length;g.reputation=Math.max(0,g.reputation-expired.length*4);g.orders=g.orders.filter(o=>o.time>0);toast('Một khách đã rời hàng chờ. Tập trung vào đơn còn lại!');}g.nextOrder-=dt;if(g.nextOrder<=0){addOrder();g.nextOrder=g.level.interval*(.8+g.rng()*.4);}if(g.helper>0){g.helper-=dt;if(g.helper<=0){if(!g.waterOff){g.stations.filter(s=>s.type==='board').forEach(s=>s.dirty=false);toast('Nam đã vệ sinh cả hai bàn.');}else toast('Nam tạm dừng: cần nước an toàn để vệ sinh.');}}g.helperCooldown=Math.max(0,g.helperCooldown-dt);
if(g.level.event&&!g.eventDone&&g.elapsed>=g.eventAt){g.eventDone=true;if(g.level.event==='water')g.waterOff=true;else g.fridgeOff=true;beep(250,.3);toast(g.waterOff?'Linh: “Nguồn nước chính gặp vấn đề. Mở nước dự phòng nhé!”':'Nam: “Tủ lạnh mất điện! Cầu dao ở góc dưới bên trái.”');}if(g.fridgeOff){g.fridgeTime+=dt;if(g.fridgeTime>25)g.stockUnsafe=true;}
g.uiClock+=dt;if(g.uiClock>.12){g.uiClock=0;updateUI();}if(g.time<=0||g.reputation<=0)finish();}
function finish(){g.running=false;g.paused=true;const passed=g.served>=g.level.target&&g.reputation>0;const stars=passed?starsFor(g.served,g.level.target,g.mistakes):0;if(passed){saved.stars[g.index]=Math.max(saved.stars[g.index]||0,stars);saved.unlocked=Math.max(saved.unlocked,Math.min(2,g.index+1));persist();}updateUI();const reviews=[...new Set(g.logs)].slice(0,3);openModal(heading(passed?'Gian hàng đã tỏa sáng!':'Cùng thử lại nhé!')+`<div class="result-stars">${'★'.repeat(stars)+'☆'.repeat(3-stars)}</div><p class="modal-copy">${passed?(g.index===2?'Cả đội đã giải cứu hội chợ! Chơi lại để thử bố cục và đơn hàng mới.':'Bạn đã hoàn thành ca bếp và mở chương tiếp theo.'):(g.reputation<=0?'Gian hàng cần tạm đóng để khắc phục.':'Chưa đủ số món cho mục tiêu. Hãy thử bố trí thứ tự công việc hiệu quả hơn.')}</p><div class="result-grid"><div><strong>${g.served}/${g.level.target}</strong>Món an toàn</div><div><strong>${g.score}</strong>Điểm phục vụ</div><div><strong>${g.mistakes}</strong>Lỗi an toàn</div></div>${reviews.length?reviews.map(t=>`<div class="review">${t}</div>`).join(''):'<div class="review">✓ Bạn đã giữ món ăn an toàn. Thử rửa tay trong lúc bếp nấu để phục vụ nhanh hơn!</div>'}<p class="sources">${g.missed} khách rời hàng · ${g.waste} món bỏ · Mã lượt ${g.seed}<br>Thời gian trong game được tăng tốc. Sổ tay giải thích các nguyên tắc ngoài đời.</p><div class="modal-buttons">${passed&&g.index<2?'<button class="primary" id="next-level">Chương tiếp theo →</button>':''}<button class="${passed?'quiet':'primary'}" id="retry">Chơi lại · lượt mới</button><button class="quiet" id="same-seed">Thử lại cùng lượt</button><button class="quiet" id="back-home">Về hội chợ</button></div>`);}
function rect(x,y,w,h,color,r=8){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function line(x1,y1,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function text(t,x,y,size=12,color=colors.ink,align='center',weight=700){ctx.fillStyle=color;ctx.font=`${weight} ${size}px "Be Vietnam Pro",system-ui,sans-serif`;ctx.textAlign=align;ctx.fillText(t,x,y);}
function icon(t,x,y,size=30){text(t,x,y,size,colors.ink);}
function foodIcon(kind,x,y,size=30,raw=false){if(sprite('food-'+kind+(raw?'-raw':''),x,y,size*1.35))return;if(kind==='chicken'){ctx.save();ctx.translate(x,y);ctx.rotate(-.5);rect(-size*.18,-size*.32,size*.5,size*.18,'#f7e8ce',5);ellipse(-size*.23,-size*.05,size*.34,size*.24,'#d99a61');ellipse(-size*.28,-size*.1,size*.21,size*.13,'#edb380');ctx.restore();}else if(kind==='salad'){ellipse(x,y+3,size*.44,size*.22,'#f4f1df');for(let i=0;i<5;i++)ellipse(x+(i-2)*size*.12,y-size*.08-Math.sin(i)*3,size*.14,size*.16,i%2?'#75a75a':'#9dc572');ellipse(x+size*.15,y-2,size*.1,size*.09,'#dd7251');}else{ctx.fillStyle='#e78069';ctx.beginPath();ctx.moveTo(x,y-size*.35);ctx.arc(x,y-size*.35,size*.55,.25,Math.PI-.25);ctx.closePath();ctx.fill();ctx.strokeStyle='#60946a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y-size*.35,size*.55,.25,Math.PI-.25);ctx.stroke();for(let i=0;i<3;i++)ellipse(x+(i-1)*size*.15,y,size*.025,size*.04,'#513f34');}}
function plant(x,y,size=1){if(sprite('plant',x,y-6,64*size))return;ellipse(x,y+10,22*size,8*size,'#233c2920');rect(x-12*size,y-3*size,24*size,23*size,'#cb9470',5);ellipse(x,y-17*size,24*size,19*size,'#91ad77');ellipse(x-12*size,y-23*size,15*size,17*size,'#7a9e68');ellipse(x+9*size,y-28*size,17*size,20*size,'#a6c184');}
function character(x,y,shirt='#e9b263',dir='down',moving=false,helper=false){if(drawCharacterSprite(x,y,dir,moving,helper))return;const bob=moving?Math.sin(g.elapsed*15)*2:0;ellipse(x,y+20,22,8,'#203c2726');const step=moving?Math.sin(g.elapsed*15)*5:0;rect(x-13,y+5+step,10,17,'#315b56',4);rect(x+3,y+5-step,10,17,'#315b56',4);rect(x-20,y-17+bob,40,32,shirt,13);rect(x-12,y-12+bob,24,28,'#f8f4df',4);rect(x-25,y-13+bob,8,23,'#efc092',4);rect(x+17,y-13+bob,8,23,'#efc092',4);ellipse(x,y-31+bob,21,22,'#efc092');ellipse(x,y-40+bob,21,17,'#3c4535');if(dir!=='up'){ellipse(x-7+(dir==='right'?7:dir==='left'?-7:0),y-30+bob,2,2.8,'#2c3c32');ellipse(x+7+(dir==='right'?7:dir==='left'?-7:0),y-30+bob,2,2.8,'#2c3c32');line(x-3,y-22+bob,x+4,y-22+bob,'#af775e',1.5);}if(!helper){rect(x-22,y-51+bob,44,12,'#f9f6e7',6);ellipse(x-12,y-57+bob,12,10,'#fffbed');ellipse(x+2,y-61+bob,14,12,'#fffbed');ellipse(x+15,y-55+bob,10,9,'#fffbed');}else rect(x-22,y-52+bob,44,11,'#7dabc2',5);}
function drawStation(s){if(drawStationSprite(s))return;const locked=(s.id==='veg'&&g.index<1)||(s.id==='fruit'&&g.index<2);const x=s.x-s.w/2,y=s.y-s.h/2;const n=nearest();const active=n?.id===s.id;if(active){rect(x-8,y-8,s.w+16,s.h+16,'#f5c875',14);rect(x-5,y-5,s.w+10,s.h+10,colors.floor,12);}rect(x+4,y+8,s.w,s.h,'#214b3820',11);if(s.type==='stock'){rect(x,y,s.w,s.h,s.kind==='chicken'?'#9bbbc0':'#b5c394',10);rect(x+7,y+7,s.w-14,s.h-20,s.kind==='chicken'?'#e2eef0':'#d8ddbf',6);if(s.kind==='chicken'){line(x+s.w/2,y+8,x+s.w/2,y+s.h-20,'#a9c2c5');rect(x+s.w/2-7,y+23,4,17,'#7d9b9c',2);rect(x+s.w/2+3,y+23,4,17,'#7d9b9c',2);foodIcon('chicken',s.x-27,s.y,25);text(g.fridgeOff?'⚡':'4°C',s.x+29,s.y+4,15,g.fridgeOff?'#b95332':'#507d7b');}else{for(let i=0;i<3;i++)foodIcon(s.kind,x+25+i*35,s.y,25);}if(locked){rect(x,y,s.w,s.h,'#e4e6d6dd',10);text('CHƯƠNG '+(s.kind==='salad'?'02':'03'),s.x,s.y+4,10,'#7f8c77');}}
else if(s.type==='sink'){rect(x,y,s.w,s.h,'#aac2b8',9);rect(x+8,y+8,s.w-16,s.h-23,'#d8e7df',6);rect(x+25,y+14,70,35,g.waterOff?'#bcc6bd':'#91c6d0',9);ellipse(x+60,y+32,6,5,'#6b9696');line(s.x+35,y+9,s.x+35,y-7,'#7b9d98',7);line(s.x+35,y-7,s.x+14,y-7,'#7b9d98',7);rect(x+8,y+11,12,23,'#eacc88',4);if(g.waterOff)text('!',s.x,s.y+7,28,'#c37344');}
else if(s.type==='board'){rect(x,y,s.w,s.h,'#b68c66',8);rect(x+5,y+4,s.w-10,s.h-17,'#e8d4ac',6);rect(x+20,y+10,70,41,s.id==='rawboard'?'#d79987':'#a7bc88',5);line(x+70,y+17,x+81,y+35,'#ecf1e6',7);line(x+81,y+35,x+85,y+45,'#506952',5);if(s.dirty){text('CẦN VỆ SINH',s.x,s.y+9,8,'#754536');rect(x+12,y+s.h-7,s.w-24,4,'#b8755d',2);}}
else if(s.type==='stove'){rect(x,y,s.w,s.h,'#749591',9);rect(x+5,y+5,s.w-10,s.h-17,'#bac9bd',7);ellipse(s.x-26,s.y-4,21,19,'#355a50');ellipse(s.x+26,s.y-4,21,19,'#355a50');ellipse(s.x-26,s.y-4,13,12,s.item?'#e6a465':'#5d7d6b');ellipse(s.x+26,s.y-4,13,12,'#5d7d6b');if(s.item){foodIcon('chicken',s.x-26,s.y-5,26);rect(x+10,y+s.h-11,s.w-20,5,'#3d6155',3);rect(x+10,y+s.h-11,(s.w-20)*Math.min(1,s.cook/COOK_SECONDS),5,'#f1bf71',3);if(s.cook>=COOK_SECONDS)text(s.item.verified?'✓ 74°C':'🌡 ĐO NHIỆT',s.x,y-12,11,'#4f7751');else{for(let i=0;i<3;i++)ellipse(s.x-28+i*15,s.y-35-Math.sin(g.elapsed*3+i)*4,4,7,'#ffffff99');}}}
else if(s.type==='serve'){rect(x,y,s.w,s.h,'#d1a478',8);rect(x+5,y+5,s.w-10,s.h-17,'#ebd1a4',7);rect(x+14,y+10,s.w-28,34,'#7ba790',5);text('NHẬN MÓN',s.x,y+32,10,'#fff9e6');ellipse(s.x,y+80,27,16,'#fdf6e4');ellipse(s.x,y+80,21,11,'#eee4c7');}
else if(s.type==='trash'){rect(x+12,y+2,s.w-24,s.h-8,'#9bada0',9);rect(x+6,y,s.w-12,14,'#6b8b79',5);text('♻',s.x,s.y+14,28,'#eff1e3');}
else if(s.type==='power'){rect(x,y,s.w,s.h,'#a4b5a3',6);rect(x+8,y+7,22,27,'#dee5d6',4);rect(x+43,y+12,17,18,g.fridgeOff?'#d88962':'#6d9974',3);text('⚡',s.x-20,s.y+10,18);}
else{rect(x,y,s.w,s.h,'#b8c9ad',9);rect(x+35,y+9,42,42,'#aacdd7',9);rect(x+43,y+3,26,10,'#f4efd7',4);text('💧',s.x,s.y+9,22);}
text(s.name,s.x,y+s.h+21,10,active?'#194f3b':'#5e7966');}
function draw(){if(!g)return;ctx.clearRect(0,0,1000,640);rect(0,0,1000,640,'#cad8bd',0);rect(30,80,940,535,'#ede9d7',18);for(let y=85;y<612;y+=45)for(let x=32;x<968;x+=45){rect(x+1,y+1,43,43,(Math.floor(x/45)+Math.floor(y/45))%2?'#f0ebda':'#e8e2cf',3);ctx.strokeStyle='#d6ceb94d';ctx.lineWidth=1;ctx.strokeRect(x,y,45,45);}rect(222,230,86,290,'#91b6a218',18);rect(717,225,76,255,'#e5b46e18',18);rect(30,70,940,24,'#a4b79a',5);rect(26,71,949,9,'#e2e7c9',4);for(let i=0;i<17;i++){ctx.fillStyle=i%3===0?'#e49c76':i%3===1?'#8bb496':'#e6c584';ctx.beginPath();ctx.moveTo(45+i*56,18);ctx.lineTo(77+i*56,18);ctx.lineTo(61+i*56,47);ctx.closePath();ctx.fill();}line(30,17,970,17,'#8c9c7e',2);text('HỘI CHỢ • GIAN HÀNG BIỆT ĐỘI',500,64,13,'#4d7057', 'center',800);plant(28,50,.8);plant(975,54,.85);plant(975,594,.9);if(!art.serve){rect(813,182,165,16,'#e2ae72',5);for(let i=0;i<6;i++)rect(817+i*27,146,27,45,i%2?'#fcf0ca':'#df9362',3);}for(let i=0;i<8;i++){ellipse(24+i*133,628,25,12,'#95ae7840');}
// customers beyond the serving counter
for(let i=0;i<Math.min(3,g.orders.length);i++){const y=260+i*95;if(art.characters){ctx.save();ctx.translate(967,y);ctx.scale(.72,.72);character(0,0,'#92abc0','left',false,i%2===0);ctx.restore();}else{ellipse(982,y+20,15,6,'#304c2622');rect(970,y-8,25,28,['#c7866a','#92abc0','#bba7c9'][i],8);ellipse(982,y-22,15,16,'#ecc399');ellipse(983,y-31,16,11,'#515342');}}
const nearestS=nearest();for(const s of [...g.stations].sort((a,b)=>a.y-b.y))drawStation(s);
if(g.helper>0){const s=g.stations.find(s=>s.id==='cleanboard');character(s.x-90,s.y,'#8fbdc5','right',false,true);text('Nam · vệ sinh',s.x-90,s.y-77,10,'#466b5a');}else{character(810,540,'#8fbdc5','left',false,true);text('Nam',810,465,11);}
character(g.player.x,g.player.y,'#efb663',g.player.dir,g.player.moving&&!g.busy);text('Linh · bạn',g.player.x,g.player.y-80,10,'#486c55');if(g.held){ellipse(g.player.x+22,g.player.y-7,19,13,'#f8f3dc');foodIcon(g.held.kind,g.player.x+22,g.player.y-9,27,['raw','washed','cut'].includes(g.held.stage));const ratio=Math.min(1,g.held.exposure/MAX_EXPOSURE);if(ratio>0){rect(g.player.x-20,g.player.y+30,40,4,'#cfceb7',2);rect(g.player.x-20,g.player.y+30,40*(1-ratio),4,ratio>.75?'#cc7958':'#719d74',2);}}if(g.busy){rect(g.player.x-49,g.player.y-105,98,11,'#bac9af',5);rect(g.player.x-49,g.player.y-105,98*(1-g.busy.seconds/g.busy.total),11,'#edb864',5);text(g.busy.label,g.player.x,g.player.y-118,10);}else if(nearestS){rect(g.player.x-17,g.player.y+36,34,25,'#174f45',7);text('E',g.player.x,g.player.y+53,13,'#fff6df');}if(walkTarget){ctx.strokeStyle='#527859';ctx.lineWidth=2;ctx.beginPath();ctx.arc(walkTarget.x,walkTarget.y,9,0,Math.PI*2);ctx.stroke();}if(g.paused){rect(0,0,1000,640,'#163c311f',0);} }
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);if(g)draw();requestAnimationFrame(frame);}
function pause(){if(!g?.running)return;openModal(heading('Nghỉ một chút')+'<p class="modal-copy">Ca bếp đã tạm dừng. Đồng hồ, khách và món trên bếp đều chờ bạn.</p><div class="modal-buttons"><button class="primary" data-close>Tiếp tục →</button><button class="quiet" id="pause-guide">Công thức</button><button class="quiet" id="back-home">Về hội chợ</button></div>',true);}
$('modal').addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.hasAttribute('data-close'))closeModal();if(el.id==='begin'){modalResume=true;closeModal();}if(el.id==='intro-guide'||el.id==='pause-guide')guide();if(el.id==='back-home'){if(g)g.running=false;modalResume=false;closeModal();renderHome();}if(el.id==='retry'){const i=g.index;closeModal();startLevel(i);}if(el.id==='same-seed'){const {index,seed}=g;closeModal();startLevel(index,seed);}if(el.id==='next-level'){const i=g.index+1;closeModal();startLevel(i);}});
$('modal').addEventListener('cancel',e=>{e.preventDefault();if(g?.running&&!modalResume){modalResume=true;}closeModal();});
$('levels').addEventListener('click',e=>{const el=e.target.closest('[data-level]');if(el&&!el.disabled)startLevel(Number(el.dataset.level));});$('quick-play').onclick=()=>startLevel(saved.unlocked);$('book').onclick=book;$('howto').onclick=guide;$('guide-play').onclick=guide;$('pause').onclick=pause;$('help').onclick=askHelper;$('interact').onclick=interact;$('touch-action').onclick=interact;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').setAttribute('aria-label',sound?'Tắt âm thanh':'Bật âm thanh');beep(660);toast(sound?'Đã bật âm thanh':'Đã tắt âm thanh');};$('brand').onclick=e=>{e.preventDefault();if(g?.running)pause();else renderHome();};
window.addEventListener('keydown',e=>{if($('modal').open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(g?.running&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','e','h','Escape'].includes(k))e.preventDefault();keys[k]=true;if(!e.repeat){if(k==='e'||k===' ')interact();if(k==='h')askHelper();if(k==='Escape')pause();}});window.addEventListener('keyup',e=>{keys[e.key.length===1?e.key.toLowerCase():e.key]=false;});window.addEventListener('blur',()=>{keys={};touch={x:0,y:0};if(g?.running&&!g.paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g?.running&&!g.paused)pause();});
for(const b of document.querySelectorAll('[data-dir]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};[touch.x,touch.y]=dirs[b.dataset.dir];});const stop=()=>touch={x:0,y:0};b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('lostpointercapture',stop);}
canvas.addEventListener('pointerdown',e=>{if(!g?.running||g.paused||g.busy)return;canvas.focus({preventScroll:true});const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*1000/r.width,y=(e.clientY-r.top)*640/r.height;const station=g.stations.find(s=>Math.abs(x-s.x)<s.w/2+10&&Math.abs(y-s.y)<s.h/2+10);if(station){const p=g.player;const choices=[{x:station.x,y:station.y+station.h/2+32},{x:station.x,y:station.y-station.h/2-32},{x:station.x-station.w/2-32,y:station.y},{x:station.x+station.w/2+32,y:station.y}].filter(p=>canMove(p.x,p.y)).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));setWalkPath(choices[0]);}else if(canMove(x,y))setWalkPath({x,y});});
renderHome();requestAnimationFrame(frame);
