import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import * as rules from '../rules.js';
function harness(){const els=new Map();const ctx=new Proxy({},{get:()=>()=>{}});const element=id=>{if(!els.has(id))els.set(id,{textContent:'',innerHTML:'',style:{},checked:false,open:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},getContext:()=>ctx,showModal(){this.open=true;},close(){this.open=false;},focus(){}});return els.get(id);};const env={...rules,document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},requestAnimationFrame(){},setTimeout:()=>0,clearTimeout(){},console};const src=readFileSync(new URL('../game.js',import.meta.url),'utf8').replace(/^import .*\n/,'');vm.createContext(env);vm.runInContext(src+`\nglobalThis.api={startLevel,interact,update,setWalkPath,nearest,closeModal,finish,askHelper,get state(){return g},get saved(){return saved},get target(){return walkTarget},get path(){return walkPath}};`,env);return env.api;}
function advance(a,seconds){for(let i=0;i<seconds*20;i++)a.update(.05);}
function station(a,id){const s=a.state.stations.find(s=>s.id===id);const positions=[{x:s.x,y:s.y+s.h/2+32},{x:s.x-s.w/2-32,y:s.y},{x:s.x+s.w/2+32,y:s.y},{x:s.x,y:s.y-s.h/2-32}];for(const p of positions){a.state.player.x=p.x;a.state.player.y=p.y;if(a.nearest()?.id===id)return;}throw Error('Unreachable station '+id);}
function use(a,id){station(a,id);a.interact();if(a.state.busy)advance(a,a.state.busy.total+.1);}
function chicken(a){use(a,'chicken');use(a,'rawboard');use(a,'stove');use(a,'sink');advance(a,8);use(a,'stove');assert.equal(a.state.stations.find(s=>s.id==='stove').item.verified,true);use(a,'stove');use(a,'serve');}
test('complete playable chicken workflow, score and unlock next chapter',()=>{const a=harness();a.startLevel(0,1);a.state.paused=false;chicken(a);assert.equal(a.state.served,1);assert.equal(a.state.mistakes,0);assert.ok(a.state.score>=100);for(let i=0;i<3;i++){a.state.orders.push({id:100+i,kind:'chicken',time:100,max:100});chicken(a);}a.finish();assert.equal(a.saved.unlocked,1);assert.ok(a.saved.stars[0]>=1);});
test('dirty hands contaminate cooked chicken and counter rejects it',()=>{const a=harness();a.startLevel(0,1);a.state.paused=false;use(a,'chicken');use(a,'rawboard');use(a,'stove');advance(a,11);use(a,'stove');use(a,'stove');use(a,'serve');assert.equal(a.state.served,0);assert.equal(a.state.mistakes,1);assert.equal(a.state.logs.length,1);});
test('water and refrigerator incidents are recoverable by actions',()=>{const a=harness();a.saved.unlocked=2;for(const [level,fix] of [[1,'water'],[2,'power']]){a.startLevel(level,5);a.state.paused=false;advance(a,70);assert.ok(a.state.waterOff||a.state.fridgeOff);use(a,fix);assert.equal(a.state.waterOff,false);assert.equal(a.state.fridgeOff,false);}});
test('tap path reaches every active station in all map variants',()=>{const a=harness();a.saved.unlocked=2;for(const level of [0,1,2])for(const seed of [1,2,3]){a.startLevel(level,seed);a.state.paused=false;for(const s of a.state.stations){a.state.player.x=370;a.state.player.y=350;const p={x:s.x,y:s.y+s.h/2+32};if(s.id==='power')p.y=s.y-s.h/2-32;a.setWalkPath(p);assert.ok(a.target,`path to ${s.id}, level ${level}, seed ${seed}`);advance(a,8);assert.ok(Math.hypot(a.state.player.x-p.x,a.state.player.y-p.y)<15,`arrival ${s.id}`);}}});
test('pause stops cooking, patience and round clock',()=>{const a=harness();a.startLevel(0,1);const before=a.state.time;advance(a,10);assert.equal(a.state.time,before);assert.equal(a.state.orders[0].time,a.state.orders[0].max);});
test('produce workflow uses safe water and clean board; helper cleans tools',()=>{const a=harness();a.saved.unlocked=2;a.startLevel(2,42);a.state.paused=false;for(const kind of ['salad','fruit']){a.state.orders.push({id:100,kind,time:100,max:100});use(a,kind==='salad'?'veg':'fruit');use(a,'sink');use(a,'cleanboard');use(a,'serve');}assert.equal(a.state.served,2);assert.equal(a.state.mistakes,0);a.state.stations.find(s=>s.id==='rawboard').dirty=true;a.askHelper();advance(a,6);assert.equal(a.state.stations.find(s=>s.id==='rawboard').dirty,false);});
test('round expiry yields a result and reputation zero cannot unlock a level',()=>{const a=harness();a.startLevel(0,1);a.state.paused=false;a.state.served=8;a.state.reputation=0;advance(a,.1);assert.equal(a.state.running,false);assert.equal(a.saved.unlocked,0);a.startLevel(0,1);a.state.paused=false;advance(a,151);assert.equal(a.state.running,false);});
test('closing the introduction resumes instead of leaving an invisible pause',()=>{const a=harness();a.startLevel(0,1);assert.equal(a.state.paused,true);a.closeModal();assert.equal(a.state.paused,false);});
